import { useState } from 'react'

type Role = 'customer' | 'founder' | 'admin' | 'driver'
type DemoItem = { id: string; name: string; detail: string; price: number; signature?: boolean; stock: number }
const menu: DemoItem[] = [
  { id: 'signature', name: 'SSU Signature Meal', detail: 'Slow-cooked chicken curry, rice and pickles', price: 17, signature: true, stock: 8 },
  { id: 'biryani', name: 'Friday Biryani', detail: 'Fragrant basmati, spiced chicken and raita', price: 24, stock: 12 },
  { id: 'family', name: 'Family Pack', detail: 'Feeds four · curry, rice, sides and salad', price: 55, stock: 4 },
  { id: 'dessert', name: 'Cardamom pudding', detail: 'Rose syrup and pistachio', price: 9, stock: 9 },
]
const dollars = (n: number) => `$${n.toFixed(2)}`

export default function DemoApp() {
  const [role, setRole] = useState<Role>('customer')
  const [screen, setScreen] = useState('discover')
  const [authOpen, setAuthOpen] = useState(false)
  const [cart, setCart] = useState<Record<string, number>>({})
  const [orderStatus, setOrderStatus] = useState('Not ordered')
  const [onboardingStep, setOnboardingStep] = useState(2)
  const [deliveryStatus, setDeliveryStatus] = useState('Assigned')
  const count = Object.values(cart).reduce((a, b) => a + b, 0)
  const subtotal = menu.reduce((sum, item) => sum + item.price * (cart[item.id] ?? 0), 0)
  const add = (id: string) => setCart(c => ({ ...c, [id]: (c[id] ?? 0) + 1 }))
  const switchRole = (next: Role) => { setRole(next); setScreen(next === 'customer' ? 'discover' : next === 'founder' ? 'apply' : 'home') }
  return <div className="preview-shell">
    <header className="app-header"><a className="brand" href="/" aria-label="SSU Australia home"><span>S<span className="arrow">↑</span>SU</span><small>AUSTRALIA</small></a><div className="preview-badge">INTERACTIVE PREVIEW · NO LIVE DATA</div><nav><button className={role === 'customer' ? 'active' : ''} onClick={() => switchRole('customer')}>Discover kitchens</button><button className={role === 'founder' ? 'active' : ''} onClick={() => switchRole('founder')}>Apply to Launch Your Kitchen</button><button className="button-small" onClick={() => setAuthOpen(true)}>Sign in</button></nav></header>
    <main>{role === 'customer' && <Customer screen={screen} setScreen={setScreen} cart={cart} add={add} count={count} subtotal={subtotal} orderStatus={orderStatus} setOrderStatus={setOrderStatus}/>} {role === 'founder' && (screen === 'apply' ? <FounderApply begin={() => setScreen('home')}/> : <Founder step={onboardingStep} setStep={setOnboardingStep}/>) } {role === 'admin' && <Admin/>} {role === 'driver' && <Driver status={deliveryStatus} setStatus={setDeliveryStatus}/>}</main>
    <footer><strong>SSU Australia</strong><span>Serve Something Unique.</span><span>The home of branded local kitchens.</span><span>Preview data only.</span><button className="internal-preview" onClick={() => switchRole(role === 'admin' ? 'driver' : role === 'driver' ? 'customer' : 'admin')}>Preview internal roles</button></footer>
    {authOpen && <PreviewAuth close={() => setAuthOpen(false)} continueAs={(next) => { setAuthOpen(false); switchRole(next) }}/>} 
  </div>
}

function PreviewAuth({ close, continueAs }:{close:()=>void;continueAs:(role:Role)=>void}) { return <div className="modal-backdrop"><section className="modal"><button className="close" onClick={close} aria-label="Close">×</button><p className="eyebrow">SSU Australia</p><h2>Sign in or create an account</h2><p>Customers sign in to order, save addresses and track orders. Founders use the same account from application through kitchen launch.</p><label>Email address<input type="email" placeholder="you@email.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary" onClick={() => continueAs('customer')}>Continue as customer in preview</button><button onClick={() => continueAs('founder')}>Continue as kitchen founder in preview</button><p className="form-footnote">Admin and Driver accounts are invited by SSU — there is no public signup for them.</p></section></div> }
function FounderApply({begin}:{begin:()=>void}) { return <section className="application-layout"><div className="intro"><p className="eyebrow">Founding Kitchens</p><h1>Be one of our first five kitchens.</h1><p>Apply to launch a new food brand in the Northern Rivers. You do not need to have everything figured out yet.</p></div><section className="panel"><h2>Apply to Launch Your Kitchen</h2><p>Start by creating your founder account. Once approved, this same account becomes your Kitchen Dashboard.</p><div className="flow-steps"><span>1. Create account</span><span>2. Submit application</span><span>3. SSU review</span><span>4. Launch your kitchen</span></div><button className="primary" onClick={begin}>Create founder account in preview</button><p className="form-footnote">The live application stores your details securely in Supabase. This preview does not collect or store information.</p></section></section> }

function Customer({ screen, setScreen, cart, add, count, subtotal, orderStatus, setOrderStatus }: { screen:string; setScreen:(s:string)=>void; cart:Record<string,number>; add:(id:string)=>void; count:number; subtotal:number; orderStatus:string; setOrderStatus:(s:string)=>void }) {
  if (screen === 'kitchen') return <section className="customer-page"><button className="back" onClick={() => setScreen('discover')}>← Discover kitchens</button><div className="kitchen-hero"><div><p className="eyebrow">SSU Founding Kitchen #001</p><h1>Priya’s Friday Table</h1><p>Indian home cooking · Ballina</p><span className="status approved">Accepting pre-orders · Friday</span></div><aside><strong>Pickup &amp; free local delivery</strong><span>Order by Thursday, 6pm</span></aside></div><div className="kitchen-columns"><section><h2>Menu</h2>{menu.map(item => <article className="menu-row" key={item.id}><div>{item.signature && <span className="signature-pill">SSU SIGNATURE · $17</span>}<h3>{item.name}</h3><p>{item.detail}</p><small>{item.stock} available tonight</small></div><div><strong>{dollars(item.price)}</strong><button className="primary" onClick={() => add(item.id)}>Add</button></div></article>)}<p className="allergen">Please tell the kitchen about allergies. Food is prepared in a kitchen that may handle common allergens.</p></section><Cart cart={cart} subtotal={subtotal} count={count} onCheckout={() => setScreen('checkout')}/></div></section>
  if (screen === 'checkout') return <section className="checkout"><button className="back" onClick={() => setScreen('kitchen')}>← Back to menu</button><h1>Checkout</h1><div className="checkout-grid"><section className="panel"><h2>How would you like your order?</h2><div className="choice selected">Local delivery <strong>FREE</strong><small>Founding Kitchens launch · Ballina zone</small></div><div className="choice">Pickup <strong>FREE</strong><small>Friday 5:30–6:00pm</small></div><label>Delivery address<input defaultValue="12 River Street, Ballina NSW 2478"/></label><label>Order note <textarea placeholder="Optional notes for the kitchen or driver"/></label></section><section className="panel"><h2>Your order</h2><OrderLines cart={cart}/><div className="total"><span>Food subtotal</span><strong>{dollars(subtotal)}</strong><span>Delivery</span><strong>FREE</strong><span>Total</span><strong>{dollars(subtotal)}</strong></div><button className="primary" onClick={() => { setOrderStatus('Paid — awaiting kitchen acceptance'); setScreen('orders') }}>Place preview order</button><p className="form-footnote">In the live product, secure Stripe checkout appears here. No card details are collected in preview mode.</p></section></div></section>
  if (screen === 'orders') return <section className="panel order-track"><p className="eyebrow">Upcoming order</p><h1>Priya’s Friday Table</h1><div className="timeline"><span className="complete">Paid</span><span>Accepted</span><span>Preparing</span><span>Out for delivery</span><span>Delivered</span></div><h2>{orderStatus}</h2><p>Your kitchen will update this order as it moves through each step.</p><button onClick={() => setScreen('discover')}>Back to discover</button></section>
  return <section className="discover"><div className="discover-head"><p className="eyebrow">Discover local kitchens</p><h1>Something good is cooking nearby.</h1><p>Independent local food brands, made to order for pickup or free local delivery during launch.</p><input aria-label="Search kitchens" placeholder="Search kitchen, dish, cuisine or suburb"/></div><div className="filters"><button className="active">All kitchens</button><button>Accepting orders</button><button>SSU Signature Meals</button><button>Ballina</button><button disabled title="SSU is launching in Ballina first">Other locations — coming soon</button></div><article className="kitchen-card"><div className="card-image">PF</div><div><p className="eyebrow">FOUNDING KITCHEN #001</p><h2>Priya’s Friday Table</h2><p>Indian home cooking · Ballina</p><p>Friday batches of generous curries, biryani and desserts.</p><button className="primary" onClick={() => setScreen('kitchen')}>View kitchen</button></div></article><p className="preview-note">This is a clearly marked preview kitchen, provided only so you can explore the product before the first real kitchens are approved.</p></section>
}
function Cart({ cart, subtotal, count, onCheckout }:{cart:Record<string,number>;subtotal:number;count:number;onCheckout:()=>void}) { return <aside className="cart panel"><h2>Your order {count ? `(${count})` : ''}</h2>{count ? <><OrderLines cart={cart}/><div className="total"><span>Food subtotal</span><strong>{dollars(subtotal)}</strong><span>Delivery</span><strong>FREE</strong><span>Total</span><strong>{dollars(subtotal)}</strong></div><button className="primary" onClick={onCheckout}>Continue to checkout</button></> : <p>Add something from this kitchen. One kitchen per order keeps service simple.</p>}</aside> }
function OrderLines({cart}:{cart:Record<string,number>}) { return <div className="order-lines">{menu.filter(i => cart[i.id]).map(i => <p key={i.id}><span>{cart[i.id]}× {i.name}</span><strong>{dollars(i.price*cart[i.id])}</strong></p>)}</div> }
function Founder({step,setStep}:{step:number;setStep:(n:number)=>void}) { const steps=['Your kitchen','Your brand','Compliance','Menu','Signature Meal','Schedule','Payments','Ready for review']; return <section><p className="eyebrow">Launch Your Kitchen</p><h1>Priya’s Friday Table</h1><div className="progress"><span style={{width:`${(step/8)*100}%`}}/></div><div className="onboarding"><aside className="panel">{steps.map((s,i)=><button className={step===i+1?'active':''} onClick={()=>setStep(i+1)} key={s}><span>{i+1}</span>{s}{i+1<step&&' ✓'}</button>)}</aside><section className="panel"><p className="eyebrow">Step {step} of 8</p><h2>{steps[step-1]}</h2>{step===3?<Compliance/>:step===4?<MenuEditor/>:step===5?<Signature/>:step===8?<ReviewReady/>:<SetupStep title={steps[step-1]}/>}<div className="step-actions"><button onClick={()=>setStep(Math.max(1,step-1))}>Back</button><button className="primary" onClick={()=>setStep(Math.min(8,step+1))}>{step===8?'Submit for review':'Save and continue'}</button></div></section></div></section> }
function SetupStep({title}:{title:string}) { return <div className="setup"><p>Complete the information for <strong>{title.toLowerCase()}</strong>. Your progress is saved in the live product.</p><label>Kitchen name<input defaultValue="Priya’s Friday Table"/></label><label>Kitchen story<textarea defaultValue="Generous Friday food, made in Ballina."/></label></div> }
function Compliance(){return <div className="checklist"><p>SSU helps record your pathway. Local authorities remain responsible for approvals.</p>{['Kitchen information and photos','Menu and allergen information','Food safety supervisor pathway','Council / food business status'].map((x,i)=><div key={x}><span>{i<2?'APPROVED':'NOT STARTED'}</span>{x}<button>View</button></div>)}</div>}
function MenuEditor(){return <div><p>Kitchen controls normal menu prices. The Signature Meal price is set by SSU.</p>{menu.slice(1).map(x=><div className="editor-row" key={x.id}><strong>{x.name}</strong><input defaultValue={x.price}/><span>Available: {x.stock}</span></div>)}<button>Add menu item</button></div>}
function Signature(){return <div className="signature-editor"><span className="signature-pill">SSU SIGNATURE MEAL · $17.00 AUD</span><h3>Slow-cooked chicken curry</h3><p>You choose the dish. SSU sets the global price. When stock reaches zero, customers see Sold Out.</p><label>Quantity available<input type="number" defaultValue="8"/></label><button>Choose another dish</button></div>}
function ReviewReady(){return <div><p>Your kitchen is nearly ready. Submit it to SSU after compliance, menu, schedule and Stripe onboarding are complete.</p><div className="status more_information_required">Stripe onboarding pending</div></div>}
function Admin(){return <section><p className="eyebrow">SSU operations</p><h1>Marketplace overview</h1><div className="metrics"><Metric label="Applications" value="1" note="awaiting review"/><Metric label="Kitchens onboarding" value="1" note="not live yet"/><Metric label="Orders today" value="0" note="preview data"/><Metric label="Delivery queue" value="0" note="no active jobs"/></div><div className="admin-grid"><section className="panel"><h2>Kitchen approval</h2><h3>Priya’s Friday Table</h3><p>Ballina · Indian home cooking</p><div className="status under_review">Under review</div><div className="review-actions"><button>Request information</button><button>Decline</button><button className="primary">Approve application</button></div></section><section className="panel"><h2>Commercial model</h2><dl><dt>Signature Meal</dt><dd>$17.00</dd><dt>SSU food fee</dt><dd>12%</dd><dt>Pickup</dt><dd>Free</dd><dt>Delivery launch</dt><dd>Free / enabled</dd></dl><button>Open settings</button></section><section className="panel"><h2>Operations queue</h2><p>No live orders or delivery jobs yet.</p><button>Manage zones</button><button>View audit log</button></section></div></section>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Driver({status,setStatus}:{status:string;setStatus:(s:string)=>void}){const stages=['Heading to kitchen','Picked up','Out for delivery','Delivered'];return <section className="driver"><p className="eyebrow">Driver workspace</p><h1>Delivery queue</h1><article className="panel"><div className="status under_review">{status}</div><h2>Priya’s Friday Table → Ballina</h2><p><strong>Pickup:</strong> 14 Tamar Street, Ballina</p><p><strong>Deliver to:</strong> 12 River Street, Ballina NSW 2478</p><p><strong>Window:</strong> Friday, 6:00–6:30pm</p><p><strong>Notes:</strong> Leave at front door if no answer.</p><div className="driver-actions">{stages.map(s=><button key={s} className={status===s?'primary':''} onClick={()=>setStatus(s)}>{s}</button>)}</div></article><p className="preview-note">Delivery actions are preview-only until real orders and driver accounts are connected.</p></section>}
